import type { RiskItem } from '../types';

const stateRisks: Record<string, RiskItem[]> = {
  AL: [
    { type: 'Tornado', severity: 'extreme', description: 'Alabama is in Dixie Alley, one of the most tornado-prone regions in the US.', seasonalMonths: [3,4,5,11,12], icon: '🌪️' },
    { type: 'Hurricane', severity: 'high', description: 'Coastal areas face hurricane threats from June through November.', seasonalMonths: [6,7,8,9,10,11], icon: '🌀' },
    { type: 'Flood', severity: 'high', description: 'Flash flooding and river flooding are common, especially in spring.', seasonalMonths: [2,3,4,5], icon: '🌊' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Frequent severe thunderstorms with hail and damaging winds.', seasonalMonths: [3,4,5,6,7,8], icon: '⛈️' },
  ],
  AK: [
    { type: 'Earthquake', severity: 'extreme', description: 'Alaska has more earthquakes than any other US state.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
    { type: 'Tsunami', severity: 'high', description: 'Coastal communities face tsunami risk from Pacific earthquakes.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🌊' },
    { type: 'Winter Storm', severity: 'extreme', description: 'Severe blizzards and extreme cold temperatures are common.', seasonalMonths: [10,11,12,1,2,3,4], icon: '❄️' },
    { type: 'Wildfire', severity: 'high', description: 'Interior Alaska sees significant wildfire activity in summer.', seasonalMonths: [6,7,8], icon: '🔥' },
    { type: 'Volcanic Eruption', severity: 'moderate', description: 'Multiple active volcanoes pose eruption risk.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🌋' },
  ],
  AZ: [
    { type: 'Extreme Heat', severity: 'extreme', description: 'Temperatures regularly exceed 110°F in summer months.', seasonalMonths: [5,6,7,8,9], icon: '☀️' },
    { type: 'Wildfire', severity: 'high', description: 'Dry conditions lead to frequent and large wildfires.', seasonalMonths: [4,5,6,7], icon: '🔥' },
    { type: 'Flash Flood', severity: 'high', description: 'Monsoon season brings dangerous flash flooding to desert areas.', seasonalMonths: [7,8,9], icon: '🌊' },
    { type: 'Dust Storm', severity: 'moderate', description: 'Haboobs (massive dust storms) can reduce visibility to zero.', seasonalMonths: [7,8,9], icon: '🌬️' },
    { type: 'Drought', severity: 'high', description: 'Persistent drought conditions affect water supply.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏜️' },
  ],
  AR: [
    { type: 'Tornado', severity: 'extreme', description: 'Arkansas is in Tornado Alley with frequent severe outbreaks.', seasonalMonths: [3,4,5,11,12], icon: '🌪️' },
    { type: 'Flood', severity: 'high', description: 'River flooding is common, especially along the Mississippi and Arkansas rivers.', seasonalMonths: [2,3,4,5,6], icon: '🌊' },
    { type: 'Ice Storm', severity: 'high', description: 'Winter ice storms can cause widespread power outages.', seasonalMonths: [12,1,2,3], icon: '🧊' },
    { type: 'Earthquake', severity: 'moderate', description: 'New Madrid Seismic Zone poses earthquake risk.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
  ],
  CA: [
    { type: 'Wildfire', severity: 'extreme', description: 'California experiences severe wildfires year-round, with peak risk in fall.', seasonalMonths: [7,8,9,10,11], icon: '🔥' },
    { type: 'Earthquake', severity: 'extreme', description: 'Located on multiple fault lines including the San Andreas Fault.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
    { type: 'Drought', severity: 'high', description: 'Prolonged droughts affect water supply and increase fire risk.', seasonalMonths: [6,7,8,9,10], icon: '🏜️' },
    { type: 'Flood', severity: 'high', description: 'Atmospheric rivers cause severe flooding, especially in winter.', seasonalMonths: [11,12,1,2,3], icon: '🌊' },
    { type: 'Landslide', severity: 'moderate', description: 'Heavy rains trigger mudslides in fire-scarred areas.', seasonalMonths: [1,2,3,4], icon: '⛰️' },
    { type: 'Tsunami', severity: 'moderate', description: 'Coastal areas face tsunami risk from Pacific earthquakes.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🌊' },
  ],
  CO: [
    { type: 'Wildfire', severity: 'extreme', description: 'Colorado experiences some of the most destructive wildfires in US history.', seasonalMonths: [5,6,7,8,9,10], icon: '🔥' },
    { type: 'Winter Storm', severity: 'high', description: 'Heavy snowstorms and blizzards are common, especially at elevation.', seasonalMonths: [10,11,12,1,2,3,4], icon: '❄️' },
    { type: 'Tornado', severity: 'moderate', description: 'Eastern plains experience tornadoes during spring and summer.', seasonalMonths: [4,5,6,7,8], icon: '🌪️' },
    { type: 'Flood', severity: 'moderate', description: 'Flash flooding common in mountain canyons and along rivers.', seasonalMonths: [5,6,7,8], icon: '🌊' },
    { type: 'Avalanche', severity: 'high', description: 'Mountain areas face avalanche danger in winter and spring.', seasonalMonths: [12,1,2,3,4], icon: '⛰️' },
  ],
  CT: [
    { type: 'Winter Storm', severity: 'high', description: 'Significant snowstorms and nor\'easters are common.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Hurricane', severity: 'moderate', description: 'Connecticut coastline is vulnerable to Atlantic hurricanes.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Flood', severity: 'moderate', description: 'River flooding and coastal flooding affect many areas.', seasonalMonths: [3,4,5,9,10,11], icon: '🌊' },
    { type: 'Tornado', severity: 'low', description: 'Occasional tornadoes occur during summer thunderstorms.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
  ],
  DE: [
    { type: 'Hurricane', severity: 'moderate', description: 'Delaware Bay and Atlantic coast vulnerable to hurricanes.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Winter Storm', severity: 'moderate', description: 'Nor\'easters bring significant snow and ice.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'moderate', description: 'Coastal and river flooding are common threats.', seasonalMonths: [3,4,5,9,10,11], icon: '🌊' },
    { type: 'Tornado', severity: 'low', description: 'Occasional tornadoes occur during severe thunderstorms.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
  ],
  FL: [
    { type: 'Hurricane', severity: 'extreme', description: 'Florida faces the highest hurricane risk in the continental US.', seasonalMonths: [6,7,8,9,10,11], icon: '🌀' },
    { type: 'Flood', severity: 'extreme', description: 'Storm surge and inland flooding from hurricanes are major threats.', seasonalMonths: [6,7,8,9,10], icon: '🌊' },
    { type: 'Tornado', severity: 'high', description: 'Florida has more tornadoes per square mile than any other state.', seasonalMonths: [2,3,4,5,6], icon: '🌪️' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Florida leads the nation in lightning strikes and thunderstorms.', seasonalMonths: [6,7,8,9], icon: '⛈️' },
    { type: 'Wildfire', severity: 'moderate', description: 'Dry spring conditions fuel wildfires in palmetto scrub and pine forests.', seasonalMonths: [2,3,4,5,6], icon: '🔥' },
  ],
  GA: [
    { type: 'Tornado', severity: 'high', description: 'Georgia experiences frequent tornado activity, especially in spring.', seasonalMonths: [3,4,5,11,12], icon: '🌪️' },
    { type: 'Hurricane', severity: 'high', description: 'Coastal Georgia faces hurricane risk from the Atlantic.', seasonalMonths: [6,7,8,9,10,11], icon: '🌀' },
    { type: 'Flood', severity: 'high', description: 'Flooding from heavy rains and tropical systems is common.', seasonalMonths: [3,4,5,6,7,8,9], icon: '🌊' },
    { type: 'Ice Storm', severity: 'moderate', description: 'Winter ice storms can paralyze the Atlanta metro area.', seasonalMonths: [12,1,2,3], icon: '🧊' },
  ],
  HI: [
    { type: 'Hurricane', severity: 'moderate', description: 'Hawaii faces occasional hurricane threats from the Central Pacific.', seasonalMonths: [7,8,9,10,11], icon: '🌀' },
    { type: 'Tsunami', severity: 'high', description: 'Located in the Pacific Ring of Fire, Hawaii faces tsunami risk.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🌊' },
    { type: 'Volcanic Eruption', severity: 'high', description: 'Active volcanoes on the Big Island can threaten communities.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🌋' },
    { type: 'Flash Flood', severity: 'high', description: 'Heavy rainfall in narrow valleys causes dangerous flash floods.', seasonalMonths: [11,12,1,2,3,4], icon: '🌊' },
    { type: 'Wildfire', severity: 'high', description: 'Dry leeward areas and grassy slopes are prone to wildfire.', seasonalMonths: [7,8,9,10,11], icon: '🔥' },
  ],
  ID: [
    { type: 'Wildfire', severity: 'extreme', description: 'Idaho experiences large, destructive wildfires in summer and fall.', seasonalMonths: [6,7,8,9], icon: '🔥' },
    { type: 'Winter Storm', severity: 'high', description: 'Heavy snowstorms and blizzards are common in mountainous areas.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Earthquake', severity: 'moderate', description: 'Idaho has active fault systems that can produce significant earthquakes.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
    { type: 'Flood', severity: 'moderate', description: 'Spring snowmelt causes flooding in river valleys.', seasonalMonths: [4,5,6], icon: '🌊' },
  ],
  IL: [
    { type: 'Tornado', severity: 'high', description: 'Illinois is in Tornado Alley with frequent destructive tornadoes.', seasonalMonths: [4,5,6,7,8], icon: '🌪️' },
    { type: 'Winter Storm', severity: 'high', description: 'Severe winter storms with heavy snow and extreme cold are common.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'high', description: 'Major rivers including the Mississippi flood regularly.', seasonalMonths: [3,4,5,6], icon: '🌊' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Severe storms with large hail and damaging winds occur frequently.', seasonalMonths: [4,5,6,7,8], icon: '⛈️' },
  ],
  IN: [
    { type: 'Tornado', severity: 'high', description: 'Indiana averages over 20 tornadoes per year.', seasonalMonths: [4,5,6,7,8], icon: '🌪️' },
    { type: 'Winter Storm', severity: 'high', description: 'Lake effect snow from Lake Michigan brings heavy snow to northern Indiana.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'high', description: 'River flooding is a regular occurrence in spring.', seasonalMonths: [3,4,5,6], icon: '🌊' },
    { type: 'Severe Thunderstorm', severity: 'moderate', description: 'Severe thunderstorms with damaging winds and hail are common.', seasonalMonths: [4,5,6,7,8], icon: '⛈️' },
  ],
  IA: [
    { type: 'Tornado', severity: 'high', description: 'Iowa is in the heart of Tornado Alley.', seasonalMonths: [4,5,6,7,8], icon: '🌪️' },
    { type: 'Flood', severity: 'high', description: 'Major flooding events regularly impact Iowa rivers and communities.', seasonalMonths: [4,5,6,7], icon: '🌊' },
    { type: 'Winter Storm', severity: 'high', description: 'Blizzards and severe winter weather are common throughout the state.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Derecho storms with widespread wind damage are a significant threat.', seasonalMonths: [5,6,7,8], icon: '⛈️' },
  ],
  KS: [
    { type: 'Tornado', severity: 'extreme', description: 'Kansas is in the core of Tornado Alley with some of the most violent tornadoes.', seasonalMonths: [4,5,6,7], icon: '🌪️' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Frequent supercell thunderstorms produce large hail and strong winds.', seasonalMonths: [4,5,6,7,8], icon: '⛈️' },
    { type: 'Drought', severity: 'high', description: 'Periodic droughts significantly impact agriculture and water supply.', seasonalMonths: [6,7,8,9], icon: '🏜️' },
    { type: 'Winter Storm', severity: 'moderate', description: 'Blizzards and ice storms affect the state periodically.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'moderate', description: 'Flash flooding and river flooding occur after heavy rains.', seasonalMonths: [5,6,7], icon: '🌊' },
  ],
  KY: [
    { type: 'Tornado', severity: 'high', description: 'Kentucky is in the tornado belt with frequent and sometimes violent tornadoes.', seasonalMonths: [3,4,5,11,12], icon: '🌪️' },
    { type: 'Flood', severity: 'high', description: 'Flash flooding in mountain hollers and river flooding are common threats.', seasonalMonths: [3,4,5,6], icon: '🌊' },
    { type: 'Ice Storm', severity: 'high', description: 'Devastating ice storms can knock out power for weeks.', seasonalMonths: [12,1,2,3], icon: '🧊' },
    { type: 'Earthquake', severity: 'moderate', description: 'New Madrid Seismic Zone poses earthquake risk to western Kentucky.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
  ],
  LA: [
    { type: 'Hurricane', severity: 'extreme', description: 'Louisiana is one of the most hurricane-vulnerable states in the US.', seasonalMonths: [6,7,8,9,10,11], icon: '🌀' },
    { type: 'Flood', severity: 'extreme', description: 'Much of Louisiana is below sea level and faces catastrophic flood risk.', seasonalMonths: [6,7,8,9,10], icon: '🌊' },
    { type: 'Tornado', severity: 'high', description: 'Louisiana experiences frequent tornado activity, especially in spring.', seasonalMonths: [3,4,5,11,12], icon: '🌪️' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Frequent severe thunderstorms with lightning and strong winds.', seasonalMonths: [3,4,5,6,7,8,9], icon: '⛈️' },
  ],
  ME: [
    { type: 'Winter Storm', severity: 'high', description: 'Maine experiences severe nor\'easters and heavy snowstorms.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Hurricane', severity: 'moderate', description: 'Remnants of Atlantic hurricanes can bring damaging winds and rain.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Flood', severity: 'moderate', description: 'Spring snowmelt and heavy rains cause river flooding.', seasonalMonths: [3,4,5,6], icon: '🌊' },
    { type: 'Wildfire', severity: 'low', description: 'Drought conditions can lead to forest fires in summer.', seasonalMonths: [7,8,9], icon: '🔥' },
  ],
  MD: [
    { type: 'Hurricane', severity: 'high', description: 'Chesapeake Bay and Atlantic coast face significant hurricane risk.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Winter Storm', severity: 'high', description: 'Nor\'easters bring heavy snow and ice to the region.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'high', description: 'Flash flooding and coastal flooding are common threats.', seasonalMonths: [3,4,5,8,9,10], icon: '🌊' },
    { type: 'Tornado', severity: 'moderate', description: 'Tornadoes associated with severe thunderstorms occur each year.', seasonalMonths: [4,5,6,7,8], icon: '🌪️' },
  ],
  MA: [
    { type: 'Winter Storm', severity: 'high', description: 'Massachusetts experiences severe nor\'easters and blizzards.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Hurricane', severity: 'moderate', description: 'New England coast faces hurricane threats from the Atlantic.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Flood', severity: 'moderate', description: 'River flooding and coastal flooding affect communities.', seasonalMonths: [3,4,5,9,10], icon: '🌊' },
    { type: 'Tornado', severity: 'low', description: 'Occasional tornadoes strike during severe thunderstorms.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
  ],
  MI: [
    { type: 'Winter Storm', severity: 'extreme', description: 'Lake effect snow from Lakes Superior, Michigan, and Huron brings heavy snowfall.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Tornado', severity: 'moderate', description: 'Michigan averages about 15 tornadoes per year.', seasonalMonths: [4,5,6,7,8], icon: '🌪️' },
    { type: 'Flood', severity: 'moderate', description: 'Spring floods are common along major rivers.', seasonalMonths: [3,4,5,6], icon: '🌊' },
    { type: 'Severe Thunderstorm', severity: 'moderate', description: 'Severe thunderstorms with damaging winds are a seasonal threat.', seasonalMonths: [4,5,6,7,8], icon: '⛈️' },
  ],
  MN: [
    { type: 'Winter Storm', severity: 'extreme', description: 'Minnesota experiences some of the most severe winter weather in the lower 48 states.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Tornado', severity: 'high', description: 'Minnesota averages about 45 tornadoes per year.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
    { type: 'Flood', severity: 'high', description: 'Spring flooding and summer flash flooding are common.', seasonalMonths: [4,5,6,7,8], icon: '🌊' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Powerful thunderstorms with large hail and strong winds.', seasonalMonths: [5,6,7,8], icon: '⛈️' },
  ],
  MS: [
    { type: 'Tornado', severity: 'extreme', description: 'Mississippi has one of the highest tornado mortality rates in the US.', seasonalMonths: [3,4,5,11,12], icon: '🌪️' },
    { type: 'Hurricane', severity: 'extreme', description: 'Gulf Coast faces direct hurricane impacts frequently.', seasonalMonths: [6,7,8,9,10,11], icon: '🌀' },
    { type: 'Flood', severity: 'high', description: 'Mississippi River and its tributaries flood regularly.', seasonalMonths: [2,3,4,5,6], icon: '🌊' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Frequent severe thunderstorm outbreaks cause widespread damage.', seasonalMonths: [3,4,5,6,7,8,9], icon: '⛈️' },
  ],
  MO: [
    { type: 'Tornado', severity: 'high', description: 'Missouri is in the tornado belt with frequent destructive tornadoes.', seasonalMonths: [4,5,6,7,8,11], icon: '🌪️' },
    { type: 'Flood', severity: 'high', description: 'Missouri and Mississippi rivers cause major flooding events.', seasonalMonths: [4,5,6,7], icon: '🌊' },
    { type: 'Winter Storm', severity: 'high', description: 'Ice storms and heavy snow are common in winter.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Earthquake', severity: 'high', description: 'New Madrid Seismic Zone poses significant earthquake risk.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
  ],
  MT: [
    { type: 'Wildfire', severity: 'extreme', description: 'Montana experiences massive wildfires in summer and fall.', seasonalMonths: [6,7,8,9], icon: '🔥' },
    { type: 'Winter Storm', severity: 'high', description: 'Severe blizzards and extreme cold temperatures.', seasonalMonths: [10,11,12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'moderate', description: 'Spring snowmelt causes flooding in river valleys.', seasonalMonths: [4,5,6], icon: '🌊' },
    { type: 'Earthquake', severity: 'moderate', description: 'Montana has active fault systems that cause earthquakes.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
    { type: 'Avalanche', severity: 'high', description: 'Mountain ranges face significant avalanche danger.', seasonalMonths: [12,1,2,3,4], icon: '⛰️' },
  ],
  NE: [
    { type: 'Tornado', severity: 'extreme', description: 'Nebraska is in the core of Tornado Alley.', seasonalMonths: [4,5,6,7], icon: '🌪️' },
    { type: 'Winter Storm', severity: 'high', description: 'Blizzards and severe winter weather are common.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'high', description: 'Major flooding along the Missouri and Platte rivers.', seasonalMonths: [4,5,6,7], icon: '🌊' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Supercell thunderstorms produce large hail regularly.', seasonalMonths: [4,5,6,7,8], icon: '⛈️' },
    { type: 'Drought', severity: 'high', description: 'Periodic droughts affect agriculture across the state.', seasonalMonths: [6,7,8,9], icon: '🏜️' },
  ],
  NV: [
    { type: 'Extreme Heat', severity: 'extreme', description: 'Las Vegas regularly records temperatures above 110°F.', seasonalMonths: [6,7,8,9], icon: '☀️' },
    { type: 'Wildfire', severity: 'high', description: 'Dry desert conditions fuel wildfires across the state.', seasonalMonths: [5,6,7,8,9], icon: '🔥' },
    { type: 'Drought', severity: 'extreme', description: 'Nevada is the driest state in the US with critical water shortage issues.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏜️' },
    { type: 'Flash Flood', severity: 'moderate', description: 'Desert flash flooding during monsoon season can be dangerous.', seasonalMonths: [7,8,9], icon: '🌊' },
    { type: 'Earthquake', severity: 'moderate', description: 'Nevada has significant seismic activity.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
  ],
  NH: [
    { type: 'Winter Storm', severity: 'high', description: 'New Hampshire experiences severe nor\'easters and heavy snow.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Hurricane', severity: 'moderate', description: 'Remnants of Atlantic hurricanes can bring significant rainfall.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Flood', severity: 'moderate', description: 'Spring snowmelt causes river flooding.', seasonalMonths: [3,4,5,6], icon: '🌊' },
    { type: 'Wildfire', severity: 'low', description: 'Drought conditions can lead to forest fires.', seasonalMonths: [7,8,9], icon: '🔥' },
  ],
  NJ: [
    { type: 'Hurricane', severity: 'high', description: 'New Jersey coast is vulnerable to Atlantic hurricanes.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Winter Storm', severity: 'high', description: 'Nor\'easters bring heavy snow and dangerous ice.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'high', description: 'Coastal flooding and river flooding are significant threats.', seasonalMonths: [3,4,5,8,9,10], icon: '🌊' },
    { type: 'Tornado', severity: 'low', description: 'Occasional tornadoes occur during severe thunderstorms.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
  ],
  NM: [
    { type: 'Wildfire', severity: 'extreme', description: 'New Mexico experiences some of the largest wildfires in US history.', seasonalMonths: [4,5,6,7], icon: '🔥' },
    { type: 'Extreme Heat', severity: 'high', description: 'Extreme heat affects the lower desert regions.', seasonalMonths: [5,6,7,8,9], icon: '☀️' },
    { type: 'Drought', severity: 'extreme', description: 'Severe drought conditions are a persistent and worsening problem.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏜️' },
    { type: 'Flash Flood', severity: 'high', description: 'Monsoon season brings dangerous flash flooding.', seasonalMonths: [7,8,9], icon: '🌊' },
    { type: 'Winter Storm', severity: 'moderate', description: 'Northern mountains receive heavy snowfall.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
  ],
  NY: [
    { type: 'Winter Storm', severity: 'high', description: 'New York experiences severe nor\'easters and lake effect snow in western regions.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Hurricane', severity: 'high', description: 'New York City and Long Island are vulnerable to Atlantic hurricanes.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Flood', severity: 'high', description: 'Flash flooding and coastal flooding are significant threats.', seasonalMonths: [3,4,5,8,9,10], icon: '🌊' },
    { type: 'Tornado', severity: 'moderate', description: 'Tornadoes occur across New York, particularly in the Hudson Valley.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
    { type: 'Extreme Heat', severity: 'moderate', description: 'Heat waves can be deadly, especially in urban areas.', seasonalMonths: [7,8], icon: '☀️' },
  ],
  NC: [
    { type: 'Hurricane', severity: 'extreme', description: 'North Carolina is one of the most hurricane-impacted states.', seasonalMonths: [6,7,8,9,10,11], icon: '🌀' },
    { type: 'Flood', severity: 'high', description: 'Inland flooding from hurricanes can be catastrophic.', seasonalMonths: [8,9,10], icon: '🌊' },
    { type: 'Tornado', severity: 'high', description: 'Hurricanes and severe thunderstorms spawn frequent tornadoes.', seasonalMonths: [3,4,5,8,9,10], icon: '🌪️' },
    { type: 'Ice Storm', severity: 'moderate', description: 'Ice storms can paralyze the Piedmont and Triad areas.', seasonalMonths: [12,1,2,3], icon: '🧊' },
    { type: 'Wildfire', severity: 'moderate', description: 'Mountain and coastal plain areas experience wildfires.', seasonalMonths: [2,3,4,11], icon: '🔥' },
  ],
  ND: [
    { type: 'Winter Storm', severity: 'extreme', description: 'North Dakota has some of the most severe winters in the US.', seasonalMonths: [10,11,12,1,2,3,4], icon: '❄️' },
    { type: 'Tornado', severity: 'moderate', description: 'Tornadoes occur regularly during spring and summer.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
    { type: 'Flood', severity: 'high', description: 'Spring flooding along the Red River and Missouri River is common.', seasonalMonths: [4,5,6], icon: '🌊' },
    { type: 'Drought', severity: 'high', description: 'Periodic droughts severely impact agriculture.', seasonalMonths: [6,7,8,9], icon: '🏜️' },
  ],
  OH: [
    { type: 'Tornado', severity: 'high', description: 'Ohio averages over 19 tornadoes per year.', seasonalMonths: [4,5,6,7,8], icon: '🌪️' },
    { type: 'Winter Storm', severity: 'high', description: 'Lake effect snow from Lake Erie affects northern Ohio.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'high', description: 'River flooding and flash flooding are common threats.', seasonalMonths: [3,4,5,6], icon: '🌊' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Severe thunderstorms with damaging winds and large hail.', seasonalMonths: [4,5,6,7,8], icon: '⛈️' },
  ],
  OK: [
    { type: 'Tornado', severity: 'extreme', description: 'Oklahoma City metro is the most tornado-impacted metro area in the world.', seasonalMonths: [4,5,6,7], icon: '🌪️' },
    { type: 'Severe Thunderstorm', severity: 'extreme', description: 'Oklahoma has more severe thunderstorm days than almost any other state.', seasonalMonths: [4,5,6,7,8], icon: '⛈️' },
    { type: 'Drought', severity: 'high', description: 'Severe droughts significantly impact agriculture and water supply.', seasonalMonths: [6,7,8,9,10], icon: '🏜️' },
    { type: 'Flood', severity: 'high', description: 'Flash flooding and river flooding follow major storm systems.', seasonalMonths: [5,6,7,8], icon: '🌊' },
    { type: 'Ice Storm', severity: 'high', description: 'Devastating ice storms can knock out power across the state.', seasonalMonths: [12,1,2,3], icon: '🧊' },
  ],
  OR: [
    { type: 'Wildfire', severity: 'extreme', description: 'Oregon experiences large and destructive wildfires in summer and fall.', seasonalMonths: [6,7,8,9,10], icon: '🔥' },
    { type: 'Earthquake', severity: 'extreme', description: 'The Cascadia Subduction Zone could produce a magnitude 9+ earthquake.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
    { type: 'Tsunami', severity: 'extreme', description: 'A Cascadia Subduction Zone earthquake would generate a major tsunami.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🌊' },
    { type: 'Winter Storm', severity: 'high', description: 'Western Oregon receives heavy rainfall; eastern Oregon gets winter blizzards.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Volcanic Eruption', severity: 'moderate', description: 'Mount Hood and other Cascades volcanoes are potentially active.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🌋' },
    { type: 'Flood', severity: 'moderate', description: 'Heavy winter rains cause flooding in western valleys.', seasonalMonths: [11,12,1,2,3], icon: '🌊' },
  ],
  PA: [
    { type: 'Flood', severity: 'high', description: 'Pennsylvania experiences frequent flash flooding and river flooding.', seasonalMonths: [3,4,5,6,7,8,9], icon: '🌊' },
    { type: 'Winter Storm', severity: 'high', description: 'Nor\'easters and winter storms bring heavy snow and ice.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Tornado', severity: 'moderate', description: 'Pennsylvania averages about 10 tornadoes per year.', seasonalMonths: [4,5,6,7,8], icon: '🌪️' },
    { type: 'Hurricane', severity: 'moderate', description: 'Remnants of Atlantic hurricanes bring heavy rain and flooding.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Severe Thunderstorm', severity: 'moderate', description: 'Severe thunderstorms with damaging winds occur regularly.', seasonalMonths: [4,5,6,7,8], icon: '⛈️' },
  ],
  RI: [
    { type: 'Hurricane', severity: 'high', description: 'Rhode Island coast is particularly vulnerable to Atlantic hurricanes.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Winter Storm', severity: 'high', description: 'Nor\'easters bring heavy snow and damaging wind.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'moderate', description: 'Coastal and river flooding are regular threats.', seasonalMonths: [3,4,5,9,10], icon: '🌊' },
    { type: 'Tornado', severity: 'low', description: 'Occasional tornadoes occur during severe thunderstorms.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
  ],
  SC: [
    { type: 'Hurricane', severity: 'extreme', description: 'South Carolina coastline is frequently in the path of Atlantic hurricanes.', seasonalMonths: [6,7,8,9,10,11], icon: '🌀' },
    { type: 'Flood', severity: 'high', description: '"1000-year" flood events have struck repeatedly in recent years.', seasonalMonths: [8,9,10], icon: '🌊' },
    { type: 'Tornado', severity: 'moderate', description: 'Tornadoes occur from thunderstorms and tropical systems.', seasonalMonths: [3,4,5,8,9,10], icon: '🌪️' },
    { type: 'Winter Storm', severity: 'moderate', description: 'Ice storms can paralyze the Upstate and Midlands areas.', seasonalMonths: [12,1,2,3], icon: '🧊' },
  ],
  SD: [
    { type: 'Winter Storm', severity: 'extreme', description: 'South Dakota experiences extreme blizzards that can strand livestock and people.', seasonalMonths: [10,11,12,1,2,3,4], icon: '❄️' },
    { type: 'Tornado', severity: 'high', description: 'South Dakota is in Tornado Alley with frequent tornado activity.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
    { type: 'Drought', severity: 'high', description: 'Periodic droughts severely impact agriculture.', seasonalMonths: [6,7,8,9], icon: '🏜️' },
    { type: 'Flood', severity: 'moderate', description: 'Spring flooding along the Missouri River and its tributaries.', seasonalMonths: [4,5,6], icon: '🌊' },
  ],
  TN: [
    { type: 'Tornado', severity: 'high', description: 'Tennessee is in the tornado belt with frequent and deadly tornadoes.', seasonalMonths: [3,4,5,11,12], icon: '🌪️' },
    { type: 'Flood', severity: 'high', description: 'Flash flooding in narrow mountain valleys and river flooding.', seasonalMonths: [3,4,5,6], icon: '🌊' },
    { type: 'Ice Storm', severity: 'high', description: 'Ice storms can be devastating, especially in eastern Tennessee.', seasonalMonths: [12,1,2,3], icon: '🧊' },
    { type: 'Earthquake', severity: 'moderate', description: 'New Madrid Seismic Zone poses earthquake risk to western Tennessee.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
  ],
  TX: [
    { type: 'Hurricane', severity: 'extreme', description: 'Texas Gulf Coast is frequently struck by major hurricanes.', seasonalMonths: [6,7,8,9,10,11], icon: '🌀' },
    { type: 'Tornado', severity: 'extreme', description: 'Texas has more tornadoes than any other state.', seasonalMonths: [4,5,6,7,8], icon: '🌪️' },
    { type: 'Flood', severity: 'extreme', description: 'Flash flooding kills more Texans than any other weather disaster.', seasonalMonths: [4,5,6,7,8,9,10], icon: '🌊' },
    { type: 'Extreme Heat', severity: 'high', description: 'Deadly heat waves regularly occur across the state in summer.', seasonalMonths: [6,7,8,9], icon: '☀️' },
    { type: 'Winter Storm', severity: 'high', description: 'Rare but devastating winter storms can overwhelm infrastructure.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Wildfire', severity: 'high', description: 'Drought conditions lead to massive wildfires across Texas.', seasonalMonths: [3,4,5,6,9,10], icon: '🔥' },
    { type: 'Drought', severity: 'high', description: 'Severe and prolonged droughts affect water supply statewide.', seasonalMonths: [6,7,8,9,10], icon: '🏜️' },
  ],
  UT: [
    { type: 'Wildfire', severity: 'extreme', description: 'Utah experiences large wildfires with increasing frequency.', seasonalMonths: [6,7,8,9], icon: '🔥' },
    { type: 'Drought', severity: 'extreme', description: 'Severe drought conditions threaten the Great Salt Lake and water supply.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏜️' },
    { type: 'Earthquake', severity: 'high', description: 'Wasatch Fault runs through the most populated areas of the state.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
    { type: 'Avalanche', severity: 'high', description: 'Utah mountains have significant avalanche danger.', seasonalMonths: [12,1,2,3,4], icon: '⛰️' },
    { type: 'Flash Flood', severity: 'high', description: 'Narrow canyon flash floods can be sudden and lethal.', seasonalMonths: [7,8,9], icon: '🌊' },
  ],
  VT: [
    { type: 'Winter Storm', severity: 'high', description: 'Vermont receives heavy snow from nor\'easters and lake effect.', seasonalMonths: [12,1,2,3,4], icon: '❄️' },
    { type: 'Flood', severity: 'high', description: 'Tropical storm remnants and spring snowmelt cause major flooding.', seasonalMonths: [4,5,6,9,10], icon: '🌊' },
    { type: 'Hurricane', severity: 'low', description: 'Remnants of Atlantic storms occasionally bring heavy rain.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Wildfire', severity: 'low', description: 'Drought conditions can lead to forest fires.', seasonalMonths: [7,8,9], icon: '🔥' },
  ],
  VA: [
    { type: 'Hurricane', severity: 'high', description: 'Virginia\'s coast and Chesapeake Bay face significant hurricane risk.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Flood', severity: 'high', description: 'Flash flooding and coastal flooding are regular threats.', seasonalMonths: [3,4,5,8,9,10], icon: '🌊' },
    { type: 'Winter Storm', severity: 'high', description: 'Nor\'easters and winter storms impact the state regularly.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Tornado', severity: 'moderate', description: 'Tornadoes associated with severe thunderstorms and tropical systems.', seasonalMonths: [4,5,6,7,8,9,10], icon: '🌪️' },
    { type: 'Earthquake', severity: 'low', description: 'Virginia has a seismic zone that can produce moderate earthquakes.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
  ],
  WA: [
    { type: 'Earthquake', severity: 'extreme', description: 'Cascadia Subduction Zone could produce a magnitude 9+ earthquake.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
    { type: 'Tsunami', severity: 'extreme', description: 'A Cascadia Subduction Zone earthquake would generate a devastating tsunami.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🌊' },
    { type: 'Wildfire', severity: 'extreme', description: 'Eastern Washington experiences massive wildfires in summer.', seasonalMonths: [6,7,8,9], icon: '🔥' },
    { type: 'Volcanic Eruption', severity: 'high', description: 'Mount Rainier is one of the most dangerous volcanoes in the US.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🌋' },
    { type: 'Winter Storm', severity: 'moderate', description: 'Western Washington gets heavy rain; eastern Washington gets blizzards.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Landslide', severity: 'high', description: 'Hillside landslides are common in rainy western Washington.', seasonalMonths: [11,12,1,2,3], icon: '⛰️' },
  ],
  WV: [
    { type: 'Flood', severity: 'extreme', description: 'West Virginia has some of the worst flooding in the US due to steep terrain.', seasonalMonths: [3,4,5,6,7,8,9], icon: '🌊' },
    { type: 'Winter Storm', severity: 'high', description: 'Heavy snow and ice storms are common in mountainous terrain.', seasonalMonths: [12,1,2,3,4], icon: '❄️' },
    { type: 'Tornado', severity: 'moderate', description: 'Tornadoes occasionally impact the state despite mountainous terrain.', seasonalMonths: [4,5,6,7,8], icon: '🌪️' },
    { type: 'Landslide', severity: 'high', description: 'Steep terrain makes landslides a common threat after heavy rain.', seasonalMonths: [3,4,5,6], icon: '⛰️' },
  ],
  WI: [
    { type: 'Winter Storm', severity: 'extreme', description: 'Wisconsin experiences severe blizzards and extreme cold temperatures.', seasonalMonths: [11,12,1,2,3], icon: '❄️' },
    { type: 'Tornado', severity: 'high', description: 'Wisconsin averages about 23 tornadoes per year.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
    { type: 'Flood', severity: 'high', description: 'Flash flooding and river flooding are regular threats.', seasonalMonths: [4,5,6,7,8], icon: '🌊' },
    { type: 'Severe Thunderstorm', severity: 'high', description: 'Powerful thunderstorms with large hail and strong winds.', seasonalMonths: [5,6,7,8], icon: '⛈️' },
  ],
  WY: [
    { type: 'Winter Storm', severity: 'extreme', description: 'Wyoming has some of the most severe winters in the lower 48 states.', seasonalMonths: [10,11,12,1,2,3,4], icon: '❄️' },
    { type: 'Wildfire', severity: 'high', description: 'Wyoming experiences large wildfires in summer months.', seasonalMonths: [6,7,8,9], icon: '🔥' },
    { type: 'Tornado', severity: 'moderate', description: 'Eastern plains experience tornado activity.', seasonalMonths: [5,6,7,8], icon: '🌪️' },
    { type: 'Earthquake', severity: 'moderate', description: 'Yellowstone supervolcano area has significant seismic activity.', seasonalMonths: [1,2,3,4,5,6,7,8,9,10,11,12], icon: '🏔️' },
    { type: 'Avalanche', severity: 'high', description: 'Mountain ranges including the Wind Rivers and Tetons face avalanche danger.', seasonalMonths: [12,1,2,3,4], icon: '⛰️' },
  ],
  DC: [
    { type: 'Hurricane', severity: 'moderate', description: 'DC area can be impacted by Atlantic hurricanes and tropical storms.', seasonalMonths: [8,9,10], icon: '🌀' },
    { type: 'Winter Storm', severity: 'high', description: 'Nor\'easters can bring significant snow and ice to the DC area.', seasonalMonths: [12,1,2,3], icon: '❄️' },
    { type: 'Flood', severity: 'moderate', description: 'Potomac River flooding affects low-lying areas.', seasonalMonths: [3,4,5,8,9,10], icon: '🌊' },
    { type: 'Extreme Heat', severity: 'moderate', description: 'Heat waves can be dangerous, especially in urban areas.', seasonalMonths: [7,8], icon: '☀️' },
  ],
};

export function getRisksForState(stateCode: string): RiskItem[] {
  const normalizedCode = stateCode.toUpperCase();
  return stateRisks[normalizedCode] || [
    { type: 'Severe Thunderstorm', severity: 'moderate', description: 'Severe thunderstorms can affect any region.', seasonalMonths: [4,5,6,7,8,9], icon: '⛈️' },
    { type: 'Flood', severity: 'moderate', description: 'Flash flooding can occur in many areas.', seasonalMonths: [3,4,5,6,7,8,9], icon: '🌊' },
    { type: 'Winter Storm', severity: 'moderate', description: 'Winter weather can impact many parts of the country.', seasonalMonths: [12,1,2,3], icon: '❄️' },
  ];
}

export const MONTH_NAMES = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export const SEVERITY_COLORS: Record<string, string> = {
  extreme: 'bg-danger/20 border-danger text-danger',
  high: 'bg-primary/20 border-primary text-primary',
  moderate: 'bg-warning/20 border-warning text-warning',
  low: 'bg-success/20 border-success text-success',
};

export const SEVERITY_BADGE: Record<string, string> = {
  extreme: 'bg-danger text-white',
  high: 'bg-primary text-white',
  moderate: 'bg-warning text-black',
  low: 'bg-success text-white',
};

export const SAFETY_TIPS: Record<string, string[]> = {
  Hurricane: [
    'Evacuate if ordered by local officials — do not wait.',
    'Board up windows and bring in outdoor furniture.',
    'Fill bathtubs with water for sanitation use.',
    'Keep a 72-hour emergency kit ready.',
    'Know your evacuation route and destination.',
  ],
  Tornado: [
    'Go to the lowest floor, interior room away from windows.',
    'A bathtub or under a staircase provides extra protection.',
    'Abandon mobile homes immediately — go to a sturdy building.',
    'If outside, find a low-lying ditch and lie flat.',
    'Have a weather radio with battery backup.',
  ],
  Earthquake: [
    'Drop, Cover, and Hold On during shaking.',
    'Stay away from windows, bookshelves, and heavy furniture.',
    'After shaking stops, check for injuries and hazards.',
    'Expect aftershocks — be prepared to take cover again.',
    'Secure heavy furniture and water heaters to walls.',
  ],
  Wildfire: [
    'Know your evacuation routes before fire season.',
    'Create defensible space around your home.',
    'Use N95 masks or respirators during smoke events.',
    'Keep gutters and roof clear of debris.',
    'Have go-bags packed and ready to leave in minutes.',
  ],
  Flood: [
    'Never walk or drive through floodwaters.',
    'Move to higher ground immediately if flooding is imminent.',
    'Keep important documents in waterproof containers.',
    'Know how to shut off utilities at your home.',
    'Consider flood insurance even outside high-risk zones.',
  ],
  'Extreme Heat': [
    'Stay in air-conditioned spaces during peak heat hours.',
    'Drink plenty of water — don\'t wait until you\'re thirsty.',
    'Check on elderly neighbors and relatives.',
    'Never leave children or pets in parked cars.',
    'Know the signs of heat stroke and heat exhaustion.',
  ],
  'Winter Storm': [
    'Stock several days of food, water, and medications.',
    'Keep extra blankets, warm clothes, and hand warmers.',
    'Have your car winterized and keep fuel topped up.',
    'Never use generators or grills indoors.',
    'Know how to safely run space heaters to prevent fires.',
  ],
  Tsunami: [
    'If you feel a strong earthquake near the coast, move inland immediately.',
    'Do not wait for an official warning if near the ocean.',
    'Move to high ground — at least 100 feet elevation.',
    'Stay away from the coast until officials give the all-clear.',
    'A tsunami is a series of waves — the first may not be the largest.',
  ],
};
